# Introduction to the mpm_la package

This numerical package is about linear algebra manipulations includes finding the determinant of a matrix, multiplying matrices, finding the adjugate matrix, finding the inverse of a matrix, and solving primary linear equations

## 1 Functions

### 1.1 mpm_la.det(a)
    This function calculates the determinant of the input matrix 'a' 'a' should be a square matrix (n x n), return None when 'a' is not a square matrix. 'a' can be a numpy array or list of list.

##### 1.1.1 An Example

In [ ]:
>>> import mpm_la
>>> a = [[2, 0, -1], [0, 5, 6], [0, -1, 1]]
>>> d = mpm_la.det(a)
>>> d
22.0

### 1.2 mpm_la.mult(a, b)
    This function calculates the multiplication of the input matrix 'a' and 'b'. The number of rows of matrix 'a' should be equal to the number of columns of 'b'. If 'a' and 'b' cannot be multiplied, it will return None. Both 'a' and 'b'can be numpy array or list of list.

##### 1.2.1 An Example

In [ ]:
>>> import mpm_la
>>> a = [[1, 2], [3, 4]]
>>> b = [[5, 1], [6, 2]]
>>> d = mpm_la.mult(a, b)
>>> d
array([[17.,  5.],
       [39., 11.]])

### 1.3 mpm_la.adj(a)
    This function is used to get the adjugate matrix of the input matrix 'a'. 'a' should be a square matrix, otherwise it will return None. 'a' can be a numpy array or list of list.

##### 1.3.1 An Example

In [ ]:
>>> import mpm_la
>>> a = [[1,0,-1],[-2,3,0],[1,-3,2]]
>>> d = mpm_la.adj(a)
>>> d
array([[6., 3., 3.],
       [4., 3., 2.],
       [3., 3., 3.]])

### 1.4 mpm_la.inv(a)
    This function is used to obtain the inverse matrix of the input matrix 'a'. 'a' should be a square matrix and the determinate of 'a' should not be 0, otherwise it will return None. 'a' can be a numpy array or list of list.

##### 1.4.1 An Example

In [ ]:
>>> import mpm_la
>>> a = [[1,0,-1],[-2,3,0],[1,-3,2]]
>>> d = mpm_la.inv(a)
>>> d
array([[2.        , 1.        , 1.        ],
       [1.33333333, 1.        , 0.66666667],
       [1.        , 1.        , 1.        ]])

### 1.5 mpm_la.solve(a)
    This function uses Cramer's method for solving the linear system equation (Ax = b). a is a square matrix and b is a single column matrix. 'a' is the coefficient matrix and b is the constant matrix. 'a' should be a square matrix and the determinate of 'a' should not be 0, otherwise it will return None. 'a' can be a numpy array or list of list.

##### 1.5.1 An Example

In [ ]:
>>> import mpm_la
>>> a = [[1, 1, 1], [-1, 1, 1],[-1, -1, 1]]
>>> b = [[1], [2], [-1]]
>>> x = mpm_la.solve(a, b)
>>> x
array([[-0.5],
       [ 1.5],
       [ 0. ]])